import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { RootState, AppThunk } from '../../store/store';
import { fetchCountries, fetchCountry,  } from '../services/countryService';
import {
  ICountry,
  FetchCountriesAPIResponse,
  FetchCountriesAPIResult,
  FetchCountryAPIResult,
} from '../models/CountryModel';
import { Continent } from '../models/ContinentModel';


export interface CountryStoreState {
  countries: ICountry[] | undefined;
  continents: Continent[] | undefined;
  searchValue: string;
  fetchAllCountriesStatus: 'idle' | 'loading' | 'failed' | 'fetched';
  fetchOneCountryStatus: 'idle' | 'loading' | 'failed' | 'fetched';
  urlCode?: string;
}

const initialState: CountryStoreState = {
  countries: undefined,
  continents: undefined,
  searchValue: '',
  fetchAllCountriesStatus: 'idle',
  fetchOneCountryStatus: 'idle',
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const fetchAllCountriesAsync = createAsyncThunk(
  'countryInput/fetchAllCountries',
  async () => {
    // const response = await fetchSearchString(searchString);
    const response = await fetchCountries();

    return (response as any).data;
  },
);
export const searchCountryAsync = createAsyncThunk(
  'countryInput/fetchCountry',
  async (countryCode:string) => {
    // const response = await fetchSearchString(searchString);
    const response = await fetchCountry(countryCode);
     console.info('countrySlice -> searchCountryAsync: ',
       '\ncountryCode: ', countryCode,
       '\nresponse:', response);
    return (response as any).data;
  },
);

export const countrySlice = createSlice({
  name: 'countryInput',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    // Use the PayloadAction type to declare the contents of `action.payload`
    setSearchValue: (state, action: PayloadAction<string>) => {
       state.searchValue = action.payload;
      console.info('countryInputSlice -> reducers -> setSearchValue: ',
        '\naction: ', action,
        '\nstate: ', state);
    },
    setCountryCodeFromURL: (state, action: PayloadAction<string>) => {
       state.urlCode = action.payload;
      console.info('countryInputSlice -> reducers -> setCountryCodeFormURL: ',
        '\naction: ', action,
        '\nstate: ', state);
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchAllCountriesAsync.pending, (state) => {
        state.fetchAllCountriesStatus = 'loading';
      })
      .addCase(fetchAllCountriesAsync.fulfilled, (state, action: {
        payload: FetchCountriesAPIResult
      }) => {
        state.fetchAllCountriesStatus = 'fetched';
        state.countries = action.payload.countries;
        state.continents = action.payload.continents;

        console.info('searchAsync.fulfilled: ',
          '\naction:', action,
          '\npayload:', action.payload,
          '\nstate:', state);

      })
      .addCase(fetchAllCountriesAsync.rejected, (state) => {
        state.fetchAllCountriesStatus = 'failed';
      })
      .addCase(searchCountryAsync.pending, (state) => {
        state.fetchOneCountryStatus = 'loading';
      })
      .addCase(searchCountryAsync.fulfilled, (state, action: {
        payload: FetchCountryAPIResult
      }) => {
        state.fetchOneCountryStatus = 'fetched';
        const countries = (state.countries)?state.countries : [];
         countries.push( action.payload.country);
         state.countries = countries;
        // state.continents = action.payload.continents;

        console.info('searchAsync.fulfilled: ',
          '\naction:', action,
          '\npayload:', action.payload,
          '\nstate:', state);

      })
      .addCase(searchCountryAsync.rejected, (state) => {
        state.fetchOneCountryStatus = 'failed';
      });
  },
});

export const {setSearchValue, setCountryCodeFromURL} = countrySlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectCountrySearchValue = (state: RootState) => state.country.searchValue;
export const selectFetchAllCountriesStatus = (state: RootState) => state.country.fetchAllCountriesStatus;
export const selectFetchOneCountryStatus = (state: RootState) => state.country.fetchOneCountryStatus;
export const selectCountries = (state: RootState) => state.country.countries;
export const selectContinents = (state: RootState) => state.country.continents;
export const selectCountryCodeInURL = (state: RootState) => state.country.urlCode;
export const getFilteredCountries = (state: RootState) => {
  const searchValue = state.country.searchValue;
  if (!searchValue) {
    return undefined;
  }
  const allCountries = state.country.countries;
  const filteredCountries = allCountries?.filter((country: ICountry) => {
    return (country.name.toLowerCase()).includes(searchValue.toLowerCase());
  });
  return filteredCountries;
};
export const getCountryFromURLCode = (state: RootState) => {
  const allCountries = state.country.countries;
  const countryCode = state.country.urlCode;
  let found;
  if (countryCode) {
    found = allCountries?.find((country: ICountry) => {
      return (country.code.toLowerCase()) === (countryCode.toLowerCase());
    });
  }
  return found;
};

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
export const setSearchValueManually =
  (searchString: string): AppThunk =>
    (dispatch, getState) => {
      const currentValue = selectCountrySearchValue(getState());
      console.info('countryInputSlice -> setSearchValueManually : ',
        '\ndispatch: ', dispatch,
        '\ngetState: ', getState,
        '\ncurrentValue: ', currentValue);
      dispatch(setSearchValue(searchString));
    };
export const setURLCodeManually =
  (countryCode: string): AppThunk =>
    (dispatch, getState) => {
      const currentValue = selectCountrySearchValue(getState());
      console.info('countryInputSlice -> setSearchValueManually : ',
        '\ndispatch: ', dispatch,
        '\ngetState: ', getState,
        '\ncurrentValue: ', currentValue);
      dispatch(setCountryCodeFromURL(countryCode));
    };

export default countrySlice.reducer;
